# Generated by Django 2.0 on 2018-03-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0012_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(max_length=32, unique=True, verbose_name='应用名称')),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='应用唯一ID')),
                ('secret', models.CharField(max_length=64, verbose_name='应用密钥')),
                ('redirect_uri', models.URLField(max_length=512, verbose_name='应用跳转URI')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='权限英文简短名称')),
                ('desc', models.CharField(max_length=20, verbose_name='权限介绍')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='scopes',
            field=models.ManyToManyField(default=None, to='App.Scope'),
        ),
    ]
