# Generated by Django 2.0 on 2018-03-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_user_email'),
        ('App', '0002_app_field_change_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_app_id', models.CharField(max_length=8, verbose_name='用户在这个app下的唯一ID')),
                ('bind', models.BooleanField(default=False, verbose_name='用户是否绑定应用')),
                ('last_auth_code_time', models.FloatField(default=0, verbose_name='上一次申请auth_code的时间，防止被多次使用')),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='secret',
            field=models.CharField(max_length=32, verbose_name='应用密钥'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.App'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
