# Generated by Django 2.0 on 2018-03-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180323_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='always',
            field=models.NullBooleanField(default=None, verbose_name='Null 可有可无 True 一直可选 False 一直不可选'),
        ),
    ]
