# Generated by Django 2.0 on 2018-04-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_app_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='user_app_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='用户在这个app下的唯一ID'),
        ),
    ]
