# Generated by Django 2.0 on 2018-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20180415_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='user_app_id',
            field=models.CharField(max_length=16, unique=True, verbose_name='用户在这个app下的唯一ID'),
        ),
    ]
