# Generated by Django 2.0 on 2018-04-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20180420_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='last_auth_code_time',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='上一次申请auth_code的时间，防止被多次使用'),
        ),
    ]
