# Generated by Django 2.0 on 2018-04-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20180423_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='last_auth_code_time',
            field=models.FloatField(default=0, verbose_name='上一次申请auth_code的时间，防止被多次使用'),
        ),
    ]
