# Generated by Django 2.0 on 2019-03-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20190301_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='mark',
            field=models.SlugField(default='0-0-0-0-0', verbose_name='1-5分评分人数'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='mark',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='此用户的打分，0表示没打分'),
        ),
    ]
