# Generated by Django 2.0 on 2019-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20190304_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='info',
            field=models.TextField(default=None, verbose_name='应用介绍信息'),
        ),
    ]
