# Generated by Django 2.0 on 2019-03-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_app_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='user_num',
            field=models.IntegerField(default=0, verbose_name='用户人数'),
        ),
    ]
