# Generated by Django 2.0 on 2019-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_app_user_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='要求英文简短名称')),
                ('desc', models.CharField(max_length=20, verbose_name='要求介绍')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='premises',
            field=models.ManyToManyField(default=None, to='App.Premise'),
        ),
    ]
