# Generated by Django 2.0 on 2019-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20190306_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premise',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='要求英文简短名称'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='权限英文简短名称'),
        ),
    ]
