# Generated by Django 2.0 on 2019-03-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20190307_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='premise',
            name='detail',
            field=models.CharField(default=None, max_length=100, verbose_name='要求详细说明'),
        ),
        migrations.AddField(
            model_name='scope',
            name='detail',
            field=models.CharField(default=None, max_length=100, verbose_name='权限详细说明'),
        ),
    ]
