# Generated by Django 2.0 on 2019-03-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20190308_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='info',
            field=models.TextField(default=None, null=True, verbose_name='应用介绍信息'),
        ),
    ]
