# Generated by Django 2.0 on 2019-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20190311_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='create_time',
            field=models.DateTimeField(default=None),
        ),
    ]
