# Generated by Django 2.2.5 on 2019-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20191008_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='detail',
            field=models.fields.CharField(default=None, max_length=100, verbose_name='权限详细说明'),
        ),
    ]
