# Generated by Django 2.2.5 on 2019-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_auto_20191009_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='test_redirect_uri',
            field=models.URLField(default=None, max_length=512, verbose_name='测试环境下的应用跳转URI'),
        ),
    ]
