# Generated by Django 5.0.3 on 2024-03-26 11:42

import SmartDjango.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_app_test_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='max_user_num',
            field=SmartDjango.models.fields.IntegerField(default=0, verbose_name='最多注册用户'),
        ),
    ]
