# Generated by Django 5.0.3 on 2024-03-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_app_max_user_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='always',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Null 可有可无 True 一直可选 False 一直不可选'),
        ),
    ]
