# Generated by Django 5.2.4 on 2025-07-05 02:26

import App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_scope_always'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={},
        ),
        migrations.AlterModelOptions(
            name='premise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userapp',
            options={},
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[App.validators.AppValidator.name], verbose_name='应用名称'),
        ),
    ]
