# Generated by Django 5.2.4 on 2025-07-05 02:26

import Config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_auto_20191008_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={},
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=100, unique=True, validators=[Config.validators.ConfigValidator.key]),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=255, validators=[Config.validators.ConfigValidator.value]),
        ),
    ]
