# Generated by Django 2.0 on 2018-03-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
