# Generated by Django 2.0 on 2018-03-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
