# Generated by Django 2.0 on 2018-04-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20180416_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qitian_modify_time',
            field=models.IntegerField(default=0, help_text='一般只能修改一次', verbose_name='齐天号被修改的次数'),
        ),
    ]
