# Generated by Django 2.0 on 2019-03-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20190303_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, verbose_name='生日'),
        ),
    ]
