# Generated by Django 2.0 on 2019-03-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20190306_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
