# Generated by Django 2.0 on 2019-03-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_image_back',
            field=models.CharField(default=None, max_length=1024, verbose_name='身份证背面照'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_image_front',
            field=models.CharField(default=None, max_length=1024, verbose_name='身份证正面照'),
        ),
        migrations.AddField(
            model_name='user',
            name='idcard',
            field=models.CharField(choices=[(0, '暂未认证'), (1, '中国大陆身份证认证'), (2, '其他地区身份认证')], default=None, max_length=18, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='user',
            name='male',
            field=models.NullBooleanField(default=None, verbose_name='是否为男性'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default=None, max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_verify_type',
            field=models.SmallIntegerField(default=0, verbose_name='实名认证类型'),
        ),
    ]
