# Generated by Django 2.0 on 2019-03-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_auto_20190319_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否通过实名认证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(choices=[(0, '中国大陆身份证认证'), (1, '其他地区身份认证')], default=None, max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_verify_type',
            field=models.SmallIntegerField(default=None, verbose_name='实名认证类型'),
        ),
    ]
