# Generated by Django 2.0 on 2019-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_auto_20190320_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_status',
            field=models.SmallIntegerField(choices=[(0, '没有认证'), (1, '自动认证阶段'), (2, '人工认证阶段'), (3, '成功认证')], default=0, verbose_name='是否通过实名认证'),
        ),
    ]
