# Generated by Django 2.0 on 2019-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_auto_20190325_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_image_back',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='身份证背面照'),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_image_front',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='身份证正面照'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(choices=[(0, '中国大陆身份证认证'), (1, '其他地区身份认证')], default=None, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_verify_type',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='实名认证类型'),
        ),
    ]
