# Generated by Django 5.0.3 on 2024-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_auto_20191008_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='是否为男性'),
        ),
    ]
