# Generated by Django 5.2.4 on 2025-07-05 02:26

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_alter_user_male'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, null=True, validators=[User.validators.UserValidator.birthday], verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, validators=[User.validators.UserValidator.password]),
        ),
        migrations.AlterField(
            model_name='user',
            name='qitian',
            field=models.CharField(default=None, max_length=20, unique=True, validators=[User.validators.UserValidator.qitian]),
        ),
    ]
