# Generated by Django 5.2.4 on 2026-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_alter_user_options_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(default=None, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_verify_type',
            field=models.SmallIntegerField(choices=[(0, '中国大陆身份证认证'), (1, '其他地区身份认证')], default=None, null=True, verbose_name='实名认证类型'),
        ),
    ]
