# Generated by Django 5.2.4 on 2026-07-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_fix_user_verify_field_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIDeviceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='qt-cli', max_length=64, verbose_name='CLI客户端名称')),
                ('device_code', models.CharField(max_length=64, unique=True, verbose_name='设备码')),
                ('user_code', models.CharField(max_length=16, unique=True, verbose_name='用户确认码')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'approved'), (2, 'denied'), (3, 'consumed')], default=0, verbose_name='授权状态')),
                ('create_time', models.FloatField(default=0, verbose_name='创建时间')),
                ('expire_time', models.FloatField(default=0, verbose_name='过期时间')),
                ('interval', models.IntegerField(default=3, verbose_name='轮询间隔')),
                ('approved_time', models.FloatField(blank=True, default=None, null=True, verbose_name='批准时间')),
                ('token_issued_time', models.FloatField(blank=True, default=None, null=True, verbose_name='令牌签发时间')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user', verbose_name='授权用户')),
            ],
        ),
    ]
